package runner;

import com.manoj.task1.internal.*;
import external.*;

public class Interface {
    public static void main(String[] args) {
        Car car=new Volkswagen();
        Volkswagen volkswagen=new Volkswagen();
        volkswagen.torque();
        car.torque();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Elonmusk elonmusk=new Billionaire();
        Billionaire billionaire=new Billionaire();
        elonmusk.intelligence();
        billionaire.intelligence();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Kia kia=new Sonet();
        Sonet sonet=new Sonet();
        kia.cost();
        sonet.cost();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Skoda skoda=new Rapid();
        Rapid rapid=new Rapid();
        skoda.speed();
        rapid.speed();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Audi audi=new Quattro();
        Quattro quattro=new Quattro();
        audi.comfort();
        quattro.comfort();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Jeffbezos jeffbezos=new Rich();
        Rich rich=new Rich();
        jeffbezos.amazon();
        rich.amazon();
        jeffbezos.blueorigin();
        rich.blueorigin();
        jeffbezos.space();
        rich.space();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Toyota toyota = new Corolla();
        Corolla corolla=new Corolla();
        toyota.corolla();
        corolla.corolla();
        toyota.camry();
        corolla.camry();
        toyota.supra();
        corolla.supra();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Bmw Bmwimpl=new Bmwimpl();
        Bmwimpl bmwimpl=new Bmwimpl();
        bmwimpl.series3();
        bmwimpl.x5();
        bmwimpl.series5();
        bmwimpl.series3();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Mercedes mercedes=new dialmer();
        dialmer dialmer=new dialmer();
        mercedes.cClass();
        dialmer.cClass();
        mercedes.eClass();
        dialmer.eClass();
        mercedes.gWagon();
        dialmer.gWagon();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Karnataka karnataka=new Dharwad();
        Dharwad dharwad=new Dharwad();
        karnataka.district();
        dharwad.district();
        karnataka.taluk();
        dharwad.taluk();
        karnataka.village();
        dharwad.village();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Mobile mobile=new Vivo();
        Vivo vivo=new Vivo();
        mobile.charger();
        vivo.charger();
        mobile.desk();
        vivo.desk();
        mobile.ram();
        vivo.ram();
        mobile.memory();
        vivo.memory();
        mobile.storage();
        vivo.storage();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Laptop laptop=new Dell();
        Dell dell=new Dell();
        laptop.dellBoot();
        dell.dellBoot();
        laptop.dellConnect();
        dell.dellConnect();
        laptop.dellShutdown();
        dell.dellShutdown();
        laptop.dellSleep();
        dell.dellSleep();
        laptop.dellUpdate();
        dell.dellUpdate();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        HP hp = new HPLaptop();
        HPLaptop hpLaptop = new HPLaptop();
        hp.hpStart();
        hpLaptop.hpStart();
        hp.hpHibernate();
        hpLaptop.hpHibernate();
        hp.hpInstallDrivers();
        hpLaptop.hpInstallDrivers();
        hp.hpWifiSetup();
        hpLaptop.hpWifiSetup();
        hp.hpPowerOff();
        hpLaptop.hpPowerOff();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Lenovo lenovo = new LenovoLaptop();
        LenovoLaptop lenovoLaptop = new LenovoLaptop();
        lenovo.lenovoLaunch();
        lenovoLaptop.lenovoLaunch();
        lenovo.lenovoRestMode();
        lenovoLaptop.lenovoRestMode();
        lenovo.lenovoSync();
        lenovoLaptop.lenovoSync();
        lenovo.lenovoPairBluetooth();
        lenovoLaptop.lenovoPairBluetooth();
        lenovo.lenovoShutdown();
        lenovoLaptop.lenovoShutdown();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Asus asus = new AsusLaptop();
        AsusLaptop asusLaptop = new AsusLaptop();
        asus.asusPowerOn();
        asusLaptop.asusPowerOn();
        asus.asusSleepMode();
        asusLaptop.asusSleepMode();
        asus.asusDriverScan();
        asusLaptop.asusDriverScan();
        asus.asusUsbConnect();
        asusLaptop.asusUsbConnect();
        asus.asusPowerDown();
        asusLaptop.asusPowerDown();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Rolex rolex = new RolexWatch();
        RolexWatch rolexWatch = new RolexWatch();
        rolex.showTime();
        rolexWatch.showTime();
        rolex.showDate();
        rolexWatch.showDate();
        rolex.adjustStrap();
        rolexWatch.adjustStrap();
        rolex.setAlarm();
        rolexWatch.setAlarm();
        rolex.startStopwatch();
        rolexWatch.startStopwatch();
        rolex.batteryStatus();
        rolexWatch.batteryStatus();
        rolex.waterproofTest();
        rolexWatch.waterproofTest();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Titan titan = new TitanWatch();
        TitanWatch titanWatch = new TitanWatch();
        titan.displayTime();
        titanWatch.displayTime();
        titan.changeTime();
        titanWatch.changeTime();
        titan.lightOn();
        titanWatch.lightOn();
        titan.stopwatchMode();
        titanWatch.stopwatchMode();
        titan.alarmSet();
        titanWatch.alarmSet();
        titan.fitnessTrack();
        titanWatch.fitnessTrack();
        titan.sleepMonitor();
        titanWatch.sleepMonitor();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Fossil fossil = new FossilWatch();
        FossilWatch fossilWatch = new FossilWatch();
        fossil.fossilTime();
        fossilWatch.fossilTime();
        fossil.fossilDate();
        fossilWatch.fossilDate();
        fossil.fossilAlarm();
        fossilWatch.fossilAlarm();
        fossil.fossilSteps();
        fossilWatch.fossilSteps();
        fossil.fossilHeartRate();
        fossilWatch.fossilHeartRate();
        fossil.fossilCharging();
        fossilWatch.fossilCharging();
        fossil.fossilReset();
        fossilWatch.fossilReset();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Casio casio = new CasioWatch();
        CasioWatch casioWatch = new CasioWatch();
        casio.showDigitalTime();
        casioWatch.showDigitalTime();
        casio.enableWorldClock();
        casioWatch.enableWorldClock();
        casio.activateSensor();
        casioWatch.activateSensor();
        casio.setTimer();
        casioWatch.setTimer();
        casio.syncBluetooth();
        casioWatch.syncBluetooth();
        casio.showCompass();
        casioWatch.showCompass();
        casio.casioBacklight();
        casioWatch.casioBacklight();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Timex timex = new TimexWatch();
        TimexWatch timexWatch = new TimexWatch();
        timex.timexTime();
        timexWatch.timexTime();
        timex.timexBattery();
        timexWatch.timexBattery();
        timex.timexLight();
        timexWatch.timexLight();
        timex.timexMode();
        timexWatch.timexMode();
        timex.timexBeep();
        timexWatch.timexBeep();
        timex.timexLap();
        timexWatch.timexLap();
        timex.timexPowerSave();
        timexWatch.timexPowerSave();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Zara zara = new ZaraDress();
        ZaraDress zaraDress = new ZaraDress();
        zara.zaraShirt();
        zaraDress.zaraShirt();
        zara.zaraPant();
        zaraDress.zaraPant();
        zara.zaraJacket();
        zaraDress.zaraJacket();
        zara.zaraTryOut();
        zaraDress.zaraTryOut();
        zara.zaraPriceTag();
        zaraDress.zaraPriceTag();
        zara.zaraFabricInfo();
        zaraDress.zaraFabricInfo();
        zara.zaraExchangePolicy();
        zaraDress.zaraExchangePolicy();
        zara.zaraStockCheck();
        zaraDress.zaraStockCheck();
        zara.zaraOfferAlert();
        zaraDress.zaraOfferAlert();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        HnM hnm = new HnMDress();
        HnMDress hnmDress = new HnMDress();
        hnm.hnmTop();
        hnmDress.hnmTop();
        hnm.hnmBottom();
        hnmDress.hnmBottom();
        hnm.hnmCoat();
        hnmDress.hnmCoat();
        hnm.hnmFittingRoom();
        hnmDress.hnmFittingRoom();
        hnm.hnmBarcodeScan();
        hnmDress.hnmBarcodeScan();
        hnm.hnmMaterialCheck();
        hnmDress.hnmMaterialCheck();
        hnm.hnmDiscountApply();
        hnmDress.hnmDiscountApply();
        hnm.hnmGiftWrap();
        hnmDress.hnmGiftWrap();
        hnm.hnmFinalBill();
        hnmDress.hnmFinalBill();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        Levis levis = new LevisDress();
        LevisDress levisDress = new LevisDress();
        levis.levisJeans();
        levisDress.levisJeans();
        levis.levisShirt();
        levisDress.levisShirt();
        levis.levisTrial();
        levisDress.levisTrial();
        levis.levisLabelRead();
        levisDress.levisLabelRead();
        levis.levisPriceScan();
        levisDress.levisPriceScan();
        levis.levisRewardCheck();
        levisDress.levisRewardCheck();
        levis.levisStyleMatch();
        levisDress.levisStyleMatch();
        levis.levisCareTips();
        levisDress.levisCareTips();
        levis.levisExitNote();
        levisDress.levisExitNote();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        LouisPhilippe lp = new LouisPhilippeDress();
        LouisPhilippeDress lpDress = new LouisPhilippeDress();
        lp.lpBlazer();
        lpDress.lpBlazer();
        lp.lpShirt();
        lpDress.lpShirt();
        lp.lpPant();
        lpDress.lpPant();
        lp.lpFitting();
        lpDress.lpFitting();
        lp.lpBillCheck();
        lpDress.lpBillCheck();
        lp.lpTailorHelp();
        lpDress.lpTailorHelp();
        lp.lpClothType();
        lpDress.lpClothType();
        lp.lpPerfumeSpray();
        lpDress.lpPerfumeSpray();
        lp.lpBillingCounter();
        lpDress.lpBillingCounter();
        System.out.println("---------------------------->>>>>>>>>>>>>>>>>>>>>>>>>>>>");
        AllenSolly as = new AllenSollyDress();
        AllenSollyDress asDress = new AllenSollyDress();
        as.asTshirt();
        asDress.asTshirt();
        as.asJoggers();
        asDress.asJoggers();
        as.asBlazer();
        asDress.asBlazer();
        as.asMirrorCheck();
        asDress.asMirrorCheck();
        as.asPriceTag();
        asDress.asPriceTag();
        as.asFabricDetails();
        asDress.asFabricDetails();
        as.asColorOption();
        asDress.asColorOption();
        as.asExchangeHelp();
        asDress.asExchangeHelp();
        as.asFinalPayment();
        asDress.asFinalPayment();














    }
}
